baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-profile'
Paginate = 3
disqusShortname = "gurusabarish"
googleAnalytics = "G-DWJJVE27WD"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "Анастасия Анисимова"
description = "Text about my cool site"
favicon = "/fav.png"
useBootstrapCDN = false
animate = true

  [params.theme]
  disableThemeToggle = false

  [params.hero]
  enable = true
  intro = "Если вы оказались на этой страничке, значит вас заинтересовало данное портфолио. Меня зовут"
  title = "Анастасия"
  subtitle = "Исследую соприкосновение людей и продуктов, созданных для людей"
  content = "UX-researcher, верящий в светлое цифровое будущее. Помимо хардов и софтов использую в работе принцип «нормально делай, нормально будет»"
  image = "/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "Резюме"
    url = "#"
    download = true
    newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://example.com"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-twitter"
url = "https://example.com"

[[params.hero.socialLinks.customIcons]]
icon = "/fav.png"
url = "https://example.com"

  [params.about]
  enable = true
  title = "Обо мне"
  image = "/images/me.png"
  content = """
Как было сказано выше, я UX-исследователь, в прошлом - социолог. Имею профильное образование, чему посвятила 6 лет счастливой молодости. 
В наличии опыт работы в сфере социальной поддержки, интернет-коммуникаций, однако последние полтора года с головой ушла в бизнес и продукт - 
вместе с командой разработки мы создаем крутые образовательные продукты (игры, платформы, курсы, интерактивные конференции). 

Мои ключевые задачи - услышать пользователя, понять, что болит и где болит, и, исходя из аналитики и тестов, предложить решение."""

    [params.about.skills]
    enable = true
    title = "Ниже перечислены наиболее часто используемые методологии, с которыми я работала в последнее время:"
    items = [ "Customer development", "Moderated UT", "Clickstream analysis", "A/B testing", "LJM/CJM", "Hallway testing", "JTBD" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "UX-researcher"
    company = "Center-Game"
    companyUrl = "https://center-game.com/"
    date = "Feb 2022 - present"
    content = """
В настоящее время я работаю в digital студии технологий для обучения на позиции UX-исследователя. Мы создаем Edutainment-продукты, сочетающие в себе образовательные и игровые функции.
В мои обязанности входит:

-разработка гипотез

-работа с ЦА (сегментирование, рекрут, поддержка связи)

-изучение особенностей и предпочтений, проведение UX-тестов на прототипах и готовых продуктах, составление LJM, CJM, персона-моделей

-создание прототипов и мудбордов для тестирования в Figma (опционально, если диз не выкроил минутку)

-написание рекомендаций по улучшению продуктов

-создание и презентация итоговых результатов заказчику или продуктовой команде
     """

      [params.experience.items.featuredLink]
      enable = true
      name = "View the project"
      url = "https://example.com"

    [[params.experience.items]]
    job = "Ведущий специалист по исследованиям"
    company = "АНО «Диалог Регионы»"
    companyUrl = "https://dialog.info/"
    date = "Nov 2020 - Feb 2022"
    content = """
Предыдущий опыт работы - должность исследователя в центре компетенций в сфере интернет-коммуникаций и цифрового диалога между властью и обществом.
В мои обязанности входило проведение социологических онлайн-опросов и фокус-групп на всех этапах исследования:
-составление технического задания
-разработка дизайна исследования
-составление анкеты/гайда, пилотирование анкеты/гайда
-рекрут ЦА (в случае проведения фокус-группы)
-проведение интервью, модерирование фокус-групп
-анализ данных (SPSS, R), составление аналитических таблиц по итогам исследования
-написание отчётов и аналитических записок
-подготовка презентаций
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Младший исследователь"
    company = "NGO Stellit"
    companyUrl = "https://example.com"
    date = "Sep 2020 - Feb 2021"
    content = """
Работала в качестве ассистента руководителя инновационных программ. В мои обязанности входило:
-участие в реализации исследований в области благополучия населения на всех этапах – от разработки идеи до представления результатов исследований и содействия внедрению их в практику
-техническая поддержка участников вебинаров и онлайн-конференций
-участие в создании онлайн -курсов, техническая поддержка студентов курса на всех этапах обучения, в т.ч. мониторинг коммуникативных потоков среди поступивших на курс
-проведение быстрых регулярных онлайн-опросов среди участников курсов о качестве получаемых услуг
-подготовка отчетной документации по проведенным исследованиям и проектам

"""

      [params.experience.items.info]
      enable = false

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

    [[params.experience.items]]
    job = "Интервьюер-транскрайбер"
    company = "Advantage Group"
    companyUrl = "www.advantagegroup.com/"
    date = "Mar 2020 - Aug 2020"
    content = """
Это была проектная работа на недогий срок. Перечень обязанностей
-проведение глубинных интервью (JBTD)
-расшифровка проведенных интервью
-ведение отчетности по проведенным интервью
"""

     
  [params.education]
  enable = true

    [[params.education.items]]
    title = "Магистр Социологии"
    date = "2018 - 2020"
   
    content = """
Кафедра прикладной и отраслевой социологии
 """
      [params.education.items.school]
      name = "Санкт-Петербургский государственный университет"
      url = "https://soc.spbu.ru/fakultet/kafedry.html"

    [[params.education.items]]
    title = "Бакалавр Социологии"
    date = "2014 - 2018"
   
    content = """
Кафедра социологии молодежи и молодежной политики
"""

      [params.education.items.school]
      name = "Санкт-Петербургский государственный университет"
      url = "https://soc.spbu.ru/fakultet/kafedry.html"

      [params.education.items.featuredLink]
      enable = true
      name = "My academic record"
      url = "https://example.com"

    [[params.education.items]]
    title = ""
    

      [params.education.items.school]
      name = "Charles University in Prague (student exchange)"
      url = "https://cuni.cz/uken-1.html"

      [params.education.items.featuredLink]
      enable = true
      url = "https://example.com"

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "UX-тестирование образовательной платформы Dior "
    content = "Несколько лет назад для корпоративного обучения сотрудников была создана персональная LMS-платформа. В последнее время активность обучающихся на этой платформе снизилась. В чем причины?"
    image = "/images/projects/profile.png"

      [params.projects.items.featured]
      name = "Подробнее"
      link = "https://www.figma.com/file/b7AYPDQ9n3yEDwLk7cZCRx/Untitled?node-id=0%3A1&t=jgNFy8WQjfF3F9L8-0"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Выявление потребностей ЦА курса “Публичные выступления”"
    content = """
У заказчика был запрос на создание онлайн-курса. ЦА данного продукта довольно широка. 
Как создать оптимальный по уровню сложности и увлекающий пользователей продукт?
"""


    image = "/images/projects/converter.jpg"

      [params.projects.items.featured]
      name = "Подробнее"
      link = "https://www.figma.com/file/b7AYPDQ9n3yEDwLk7cZCRx/Untitled?node-id=3%3A32&t=jgNFy8WQjfF3F9L8-0"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "UX-тестирование образовательной платформы М-Видео"
    content = "Для обучения сотрудников был создан корпоративный образовательный портал. Отвечает ли он запросам ЦА? Закрывает ли их боли в сфере образования?"
    image = "/assets/images/1_картинка.jpeg"

      [params.projects.items.featured]
      name = "Подробнее"
      link = "https://www.figma.com/file/b7AYPDQ9n3yEDwLk7cZCRx/Untitled?node-id=3%3A69&t=jgNFy8WQjfF3F9L8-0"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "gurusabarisha@gmail.com"
  btnName = "Mail me"

[params.footer.recentPosts]
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com"
linkedin = "https://linkedin.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false
