########################
# LEFT SIDE HERO SOCIAL
########################
[[params.social]]
icon = "ti-facebook"
name = "Facebook"
URL = "#"

[[params.social]]
icon = "ti-linkedin"
name = "LinkedIn"
URL = "www.linkedin.com/in/anastasiya-anisimova"
